info:
  contact: {}
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: Returns a PONG
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Returns a PONG
      tags:
      - SampleController
  /publicmessage:
    get:
      consumes:
      - application/json
      description: Returns a sample string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Shows a string
      tags:
      - SampleController
swagger: "2.0"
